// Color palette presets with poetic Japanese names
const PRESET_THEMES = [
  // --- やわらかく、女性らしい ---
  { id: 'spring-clover',    name: '春のクローバー',       accent: '#A6B5A5', base: '#F4EBDA', text: '#262724' },
  { id: 'dried-flower',     name: 'ドライフラワー',        accent: '#CCB3B7', base: '#E6E8F1', text: '#22292C' },
  { id: 'peach-latte',      name: 'ピーチラテ',           accent: '#D5BDAE', base: '#EBE9EA', text: '#34251F' },
  { id: 'rose-biscuit',     name: 'ローズビスケット',      accent: '#E4C1B5', base: '#EAE6E1', text: '#544C40' },
  { id: 'misty-shore',      name: '霞の海辺',             accent: '#769CBF', base: '#E6E5E4', text: '#25271F' },
  { id: 'sugar-rose',       name: '砂糖漬けのバラ',        accent: '#D99AAD', base: '#E9E3EB', text: '#2D2E1B' },
  { id: 'italian-kitchen',  name: 'イタリアのピザ屋さん',  accent: '#CF7F72', base: '#EFDDD5', text: '#482019' },
  { id: 'forest-shade',     name: '森の木陰',             accent: '#627962', base: '#F1ECEB', text: '#363427' },
  { id: 'caramel-latte',    name: 'キャラメルラテ',        accent: '#CD8858', base: '#EFE8E4', text: '#412E27' },
  { id: 'aloe-morning',     name: 'アロエの朝',           accent: '#ABBAA9', base: '#F6FAF5', text: '#2C2319' },
  { id: 'cherry-petal',     name: '桜の花びら',           accent: '#DC9F95', base: '#FFF6EE', text: '#664B4F' },
  { id: 'antique-paper',    name: '古書の香り',           accent: '#CBA890', base: '#EFE9E6', text: '#2D2A29' },
  { id: 'lemon-scone',      name: 'レモンスコーン',        accent: '#D49B65', base: '#F4EAEA', text: '#493024' },
  { id: 'lavender-dusk',    name: '薄紫の夕暮れ',         accent: '#A883A9', base: '#FDECED', text: '#8A604D' },
  { id: 'vanilla-cafe',     name: 'バニラカフェ',          accent: '#D6BDA5', base: '#FFFEF9', text: '#6C6059' },
  { id: 'cinnamon-roll',    name: '焼きたてシナモン',      accent: '#D58A6A', base: '#FDFFFA', text: '#8F6140' },
  { id: 'lavender-dream',   name: 'ラベンダーの夢',        accent: '#9EC2C2', base: '#F8F4F2', text: '#5D4E72' },
  { id: 'moss-cobble',      name: '苔むす石畳',           accent: '#859A93', base: '#FFFCF7', text: '#544739' },

  // --- 落ち着いた、大人な ---
  { id: 'antique-gold',     name: 'アンティークゴールド',  accent: '#9F9460', base: '#EFF0F0', text: '#31371B' },
  { id: 'deep-rose',        name: '深紅のバラ',           accent: '#AA4D53', base: '#F7F6F6', text: '#4C2F3B' },
  { id: 'london-fog',       name: 'ロンドンの霧',         accent: '#A296AF', base: '#F1F1F1', text: '#423929' },
  { id: 'atlantic-night',   name: '大西洋の夜',           accent: '#135389', base: '#FBFEFF', text: '#30343A' },
  { id: 'brick-alley',      name: '煉瓦の路地',           accent: '#A92708', base: '#E9E3DD', text: '#3C0F0A' },
  { id: 'damask-rose',      name: 'ダマスクの薔薇',        accent: '#922951', base: '#EDEDED', text: '#4B3C39' },
  { id: 'retro-cafe',       name: 'レトロ喫茶',           accent: '#446E72', base: '#E6E4E0', text: '#2B2721' },
  { id: 'sunlit-veranda',   name: 'ひだまりの縁側',        accent: '#D89323', base: '#FFF9F4', text: '#33362F' },
  { id: 'planetarium',      name: '星空のプラネタリウム',   accent: '#344699', base: '#FBFCFF', text: '#2B262E' },
  { id: 'grassland-dusk',   name: '草原の夕暮れ',         accent: '#365C3B', base: '#FFF3E7', text: '#43311F' },
  { id: 'canvas-tote',      name: 'カーキのキャンバス',    accent: '#746F57', base: '#F9F9F8', text: '#2E2214' },
  { id: 'chocolate-shop',   name: 'チョコレートショップ',  accent: '#955A41', base: '#FAFAFA', text: '#342721' },
  { id: 'night-library',    name: '夜の図書館',           accent: '#6F789D', base: '#F3F3F3', text: '#35322E' },
  { id: 'ireland-hills',    name: 'アイルランドの丘',      accent: '#5F7F67', base: '#FDFDFD', text: '#2C4242' },
  { id: 'desert-sunset',    name: '砂漠のサンセット',      accent: '#D2986A', base: '#FFF6EC', text: '#4B4D37' },
  { id: 'mediterranean',    name: '地中海の港',           accent: '#00536D', base: '#FFF3E3', text: '#592D13' },

  // --- 明るく、爽やかな ---
  { id: 'roman-sunset',     name: 'ローマの夕焼け',        accent: '#E7674C', base: '#FEFFFA', text: '#444949' },
  { id: 'marmalade-jam',    name: 'マーマレードジャム',    accent: '#E8854A', base: '#FDFDFD', text: '#4C3725' },
  { id: 'peppermint-soda',  name: 'ペパーミントソーダ',    accent: '#28A6A5', base: '#F9FCFD', text: '#082627' },
  { id: 'spring-bud',       name: '春の新芽',             accent: '#9CA00E', base: '#F8EFE5', text: '#262015' },
  { id: 'valencia-orange',  name: 'バレンシアオレンジ',    accent: '#E97F12', base: '#FBFCFD', text: '#4D4535' },
  { id: 'strawberry-mousse',name: '苺のムース',            accent: '#D86F87', base: '#E6E5E2', text: '#595851' },
  { id: 'straw-hat',        name: '麦わら帽子',           accent: '#B4BC4E', base: '#FFFBEC', text: '#6B5E56' },
  { id: 'burnt-caramel',    name: '焦がしキャラメル',      accent: '#DB6010', base: '#FFEEDB', text: '#5B2908' },
  { id: 'poppy-field',      name: 'ポピー畑',             accent: '#CB5457', base: '#FDF7F5', text: '#515D46' },
  { id: 'fresh-basil',      name: 'フレッシュバジル',      accent: '#007A02', base: '#FDFDFD', text: '#473927' },
  { id: 'sunflower-eve',    name: '夕方のひまわり',        accent: '#E9A02A', base: '#F6ECDC', text: '#5F5434' },
  { id: 'wild-strawberry',  name: '野いちご',             accent: '#D04337', base: '#FFFCF9', text: '#96705C' },
  { id: 'peach-season',     name: '桃の季節',             accent: '#E27447', base: '#F8F8F8', text: '#443D3A' },
  { id: 'flamenco',         name: '情熱のフラメンコ',      accent: '#CF2B0E', base: '#F8FBFD', text: '#1E211B' },
  { id: 'amethyst-forest',  name: 'アメジストの森',        accent: '#A05CB0', base: '#FDF6F8', text: '#5B4945' },
  { id: 'marine-border',    name: 'マリンボーダー',        accent: '#DD4A33', base: '#FFFCFC', text: '#3B535F' },
];

if (typeof module !== 'undefined') module.exports = { PRESET_THEMES };
